# Generated by Django 5.2.3 on 2025-06-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("msg_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=14)),
                ("address", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=200)),
            ],
        ),
    ]
