# Generated by Django 5.2.3 on 2025-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookNow",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=14)),
                ("address", models.CharField(max_length=50)),
                ("place", models.CharField(max_length=50)),
                ("home", models.CharField(max_length=30)),
            ],
        ),
    ]
