# Generated by Django 5.2.3 on 2025-06-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0002_booknow"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddPlace",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="house/images/place")),
                ("place_name", models.TextField()),
                ("about_place", models.TextField()),
                ("place_loacation", models.TextField()),
                ("city", models.TextField()),
            ],
        ),
    ]
