# Generated by Django 5.2.3 on 2025-06-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0003_addplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="addplace",
            name="sub_image",
            field=models.ImageField(default="", upload_to="house/images/place"),
        ),
    ]
