# Generated by Django 5.2.3 on 2025-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0004_addplace_sub_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addplace",
            old_name="sub_image",
            new_name="sub_image1",
        ),
        migrations.AddField(
            model_name="addplace",
            name="sub_image2",
            field=models.ImageField(default="", upload_to="house/images/place"),
        ),
        migrations.AddField(
            model_name="addplace",
            name="sub_image3",
            field=models.ImageField(default="", upload_to="house/images/place"),
        ),
    ]
