# Generated by Django 5.2.3 on 2025-06-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0005_rename_sub_image_addplace_sub_image1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("villa_appartment", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="AddVillaApartment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="house/images/house")),
                ("sub_image1", models.ImageField(upload_to="house/images/home")),
                ("sub_image2", models.ImageField(upload_to="house/images/home")),
                ("sub_image3", models.ImageField(upload_to="house/images/home")),
                ("villa_or_apartment_name", models.TextField()),
                ("about", models.TextField()),
                ("loacation", models.TextField()),
                ("city", models.TextField()),
                ("bed", models.CharField(max_length=14)),
                ("washroom", models.CharField(max_length=14)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="house.type"
                    ),
                ),
            ],
        ),
    ]
