# Generated by Django 5.2.3 on 2025-06-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0007_customerreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="addplace",
            name="image_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="addplace",
            name="sub_image1_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="addplace",
            name="sub_image2_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="addplace",
            name="sub_image3_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="addvillaapartment",
            name="image_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="addvillaapartment",
            name="sub_image1_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="addvillaapartment",
            name="sub_image2_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="addvillaapartment",
            name="sub_image3_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customerreview",
            name="image_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
